### PR TITLE
Add exclude_files.txt feature

### LINKED ISSUE #28: spell-checking all markdown files?
Hey @cansavvy I've suddenly got a bunch of new spelling errors coming from my README, LICENSE, CONTRIBUTING files, and the About pages, which weren't previously being checked.  Is that the plan going forward?  Or are you going to exclude any of those?

Wondering if I should go start updating my `dictionary.txt` files, or just wait it out.

### PR DESCRIPTION
**Pull request by cansavvy**
## Summary 

Need to add documentation somewhere but the idea here is that someone can add files they'd like to ignore in the "exclude_files.txt" file. Much like the dictionary.txt and "ignore-urls.txt" file. 

This should resolve #28

### CODE REVIEW

**Review by KatherineCox — COMMENTED** [review]
One thing I notice is that you're excluding "About.Rmd" in the script, but I'm getting spell-check hits for the "About.md" file that's produced from the Rmd.  2 suggestions:

1. Now that an "exclude_files.txt" exists, put "About.Rmd" (and "About.md") in it instead of hardcoding its exclusion into the scripts.  This gives people more flexibility - they could decide to include it if they want to spell-check their contributors names, or could choose to rename the file (I wanted to do this at one point, but didn't because spell-check errors made it more work than just a file rename).
2. More generally, any .Rmds that get excluded will also need their corresponding ".mds" excluded.  It's not hard to manually list both in exclude_files.txt, but that seems like something that could be handled automatically?

**Comment by cansavvy** [comment]
Ah great point. I will try to make it so files that are excluded are excluded on all their types.

Also totally forgot about excluding About.Rmd. Should probably delete that part and let people exclude it themselves.

Thanks!

**Comment by cansavvy** [comment]
@KatherineCox See how you feel about this set up!

**Review by KatherineCox — APPROVED** [review]
I've not run the code or anything, but from reading it LGTM!
Nice that `exclude_files.txt` can accept regex.

Thanks!

**Pull request merged**
